### PR TITLE
Fix to work with rails 6.1

### PR DESCRIPTION
**Pull request by nrw505**
Rails 6.1 removed `where_clause_factory`, and calls `build_where_clause` instead, so do that if there is no `where_clause_factory` method.

### CODE REVIEW

**Comment by ReneB** [comment]
Thanks for the Pull request so far! I'm trying to get the appraisals and Travis working again so I can make sure everything still works, but currently there's a lot of `bundle exec` and local gems and global gems and such going on. I've at least successfully moved to travis-ci.com rather than .org now, so that's step 1.

Just know I appreciate the PR and am not ignoring it, but I haven't been actively developing in Ruby over the last couple of years and now I need to get it working in either my WSL environment which is... interesting... or travis.com which is also bugging me a bit.

**Comment by nrw505** [comment]
No worries - I was hoping the PR would kick off a travis run so I could see what it it broke in older rails versions but I'll see what I can manage to get going locally :)

**Comment by ReneB** [comment]
It should have, and would have, way back when - but apparently too many things changed with Travis moving and such.

I am personally fine with only maintaining forward compatibility on the main branch, because the only updates that happen to this gem are done to make it compatible with newer versions of Rails. So if it were compatible with, say, ActiveRecord 6.0 and 6.1, I think that should be good enough - there is already a version out there that works with older versions of ActiveRecord and freezing the dependency in the Gemfile should be simple enough.

If I were to do that though, I might consider "bumping versions" all the way to the current version of ActiveRecord - so, say, activerecord-like 6.0 - to properly signal compatibility with its "parent" gem. And if I were to do that, I'd probably also re-release an older version as activerecord-like 5.0.

Just thinking aloud here, but would appreciate your thoughts.

**Comment by nrw505** [comment]
Given that there's not actually that much difference between the various active record versions, at least as far as this gem goes - it's probably more work to remove support for the old versions than it is to keep it - and once you're testing against multiple rails versions anyway, testing against five rails versions is no more effort than testing against two.

**Comment by ReneB** [comment]
It's not a lot of _effort_, I agree, but I saw the build matrix on Travis and with 5 Ruby versions times 5 Rails versions times 3 databases, every commit or pull request kicked off a grand total of 75 builds. That's a bit too much for my liking, since I try to be at least a bit environmentally aware.

Also, I wouldn't actively _remove_ support, it would just not be guaranteed for newer versions.

**Comment by nrw505** [comment]
Oh right, I misunderstood. I think testing with just the last two rails versions and whichever ruby versions they require would be sufficient.

**Comment by PikachuEXE** [comment]
Would this be finished and released soon?
We have rails 7.0 already but this gem still not working with rails 6.1 😬

**Comment by ReneB** [comment]
Thanks for the reminder @PikachuEXE!

Last time I worked on this, I just couldn't get it to work properly with Travis, since Travis has changed quite a lot since I last worked with it. But I bit down again for a couple of hours and the latest build seems to finally work. I've pushed a new gem to rubygems.org and gave it a version number that clarifies that it's supposed to be used with ActiveRecord 6.1.

Seeing as how the `X.0` versions of Rails are normally backwards compatible with the last `(X-1).Y` version (is that still the case nowadays?), I expected this to work for ActiveRecord 7.0 as well. I've started a new branch that only tests against ActiveRecord 7.0, without any code changes so far. However, I quickly found out that some tests are failing. I'll check later, but it seems to be caused by the tests looking too closely at the internals - the tests that check the behavior seem to work well.

I'll see if I can spare some time soon to fix the tests to be compatible with ActiveRecord 7.0 soon, but I expect that the 6.1 version of the gem will work with ActiveRecord 7.0 as well.

**Comment by PikachuEXE** [comment]
Great!
I think rails 6.1 is more urgently needed.
rails 7.0 is released less than a month but if that's supported it's a great plus!

**Comment by ReneB** [comment]
Status update for clarity:
* activerecord-like 6.1 works with activerecord 6.1
* activerecord-like 6.1 is expected to work with activerecord 7.0 as well, but the tests report a failure. That issue seems to have no impact on the _functionality_ but rather on the internals that are being used. All tests that verify functionality actually pass.
* once I get around to fixing the tests, I plan to release activerecord-like 7.0 to be "officially" compatible with activerecord 7.0.

In the mean time, if anyone tests activerecord-like 6.1 with activerecord 7.0 and finds issues, please report them. I would probably need help to fix them in that case, but at least we'll know.

**Pull request closed without merging**
