### PR TITLE
Rails 5.2

### PR DESCRIPTION
**Pull request by robotdana**
The way WhereClause receives bind parameters are handled was changed in
rails/rails@213796f#diff-c9d167bac00ff2f45c5b5e035e8a80e8

Not passing the bind params seems to "just work", I only had to change the unit tests that directly called .binds

I don't really understand how WhereClause works I just poked at it and made assumptions

### CODE REVIEW

**Comment by robotdana** [comment]
Feel free to just go with the first commit and not Appraise everything! commit, I just wanted to be sure

**Comment by robotdana** [comment]
My naïve attempt at fixing for 5.2 wasn't great: 

```ruby
Foo.where.like(bar: '%bar_value%').where(baz: 'baz_value')
```
becomes:
```sql 
SELECT * FROM Foo WHERE bar LIKE '%bar_value%' AND baz LIKE '%bar_value%'
```

(ignoring all the actual bind parameters and escaping nonsense)

**Comment by robotdana** [comment]
Are there any issues with merging this?

**Comment by ReneB** [comment]
Hi @robotdana ,

Yes, there are, I should have responded earlier but all the builds are failing in Travis. I've been idly staring at the screen to come up with a way to fix it but it turns out that I'm not sure what causes the issue. It turns out that the Travis build expects certain Gemfiles to be present and they're not, and now I'm trying to figure out how I can add a commit to this PR that adds the right Gemfiles in `travis.yml`... I'll get back to you soon.

Thanks so far, I'll get this done soon!

**Comment by robotdana** [comment]
Thanks for that :)

Sorry my overenthusiasm broke things

**Comment by ReneB** [comment]
Hey, don't mention it. I'm happy for the PR and the fact that the gem has now been updated again for Rails 5.2, so thank _you_ instead.

Everything seems to work properly now, so I'm merging this. Thanks for giving the gem yet another lease on life!

**Pull request merged**
