### PR TITLE
* Support ActiveRecord 5.x and drop support for 4.x

### LINKED ISSUE #8: undefined method `where_values' error is occured
In rails 5 and ruby 2.4.0 `where_values` is undefined.
And I fount [`where_values` is deprecated](https://github.com/DockYard/postgres_ext/issues/180#issuecomment-186170500).

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #8

### CODE REVIEW

**Comment by ReneB** [comment]
You, @PikachuEXE, are a complete hero. I'll check this out later today. I had succeeded in getting everything to work, except for a pesky issue for the `where.like(attribute: [ 'array', 'with', ',multiple', 'strings'])`-syntax.

**Comment by ReneB** [comment]
Thanks a lot! I liked the Appraisal-related changes as well, so I've just merged them as well. I didn't know how to fix the last couple of tests, but you used a completely different approach and it works brilliantly.

**Comment by PikachuEXE** [comment]
By "last couple of tests" you mean ruby head?
I guess let's think about when 2.5.0 preview is out

**Comment by ReneB** [comment]
Hey @PikachuEXE, no I was referring to the tests for the `where.like(attribute: [ 'array', 'with', ',multiple', 'strings'])` syntax. I was referring to when I tried to update the gem over the weekend and couldn't get it done 👎

**Comment by PikachuEXE** [comment]
If array support is too difficult to maintain maybe it should be dropped in next breaking version

rails 5 got `or` now

**Comment by ReneB** [comment]
That's a very good point, `or` would be a nice replacement for a lot of what the Array syntax covers - although I do dislike the `User.where.like(name: `%something%').or(User.where.like(name: '%other%'))`-syntax, the real usage would probably be something more like:

```ruby
names.inject(User.none) do |memo, name|
  memo.or(User.where.like(name: "%#{name}%"))
end
```

which seems nice.

Of course, this code could probably be encapsulated in the gem as well, to make things work again. I'm just not too familiar with Arel itself, which makes building these Arel trees a little hard.

I'll consider it, next time we break a build. Thanks for the suggestion!

**Pull request merged**
